### ISSUE TITLE
'gbk' codec can't decode

### ISSUE THREAD

**Issue by HandsomeXi** [holymonk/AlipayTinyAppCrack#2]
不是很熟悉py
执行后报错 jscode = "".join(fp) -> UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 5: illegal multibyte sequence
然后我把代码改为jscode = fp
执行后报错
Traceback (most recent call last):
  File "E:/workspace/python/untitled/src/frida_main.py", line 19, in <module>
    process = frida.get_usb_device().attach('com.eg.android.AlipayGphone:lite1')
  File "E:\workspace\python\untitled\venv\lib\site-packages\frida\__init__.py", line 82, in get_usb_device
    return get_device_matching(lambda d: d.type == 'usb', timeout, **kwargs)
  File "E:\workspace\python\untitled\venv\lib\site-packages\frida\__init__.py", line 90, in get_device_matching
    return get_device_manager().get_device_matching(predicate, timeout, **kwargs)
  File "E:\workspace\python\untitled\venv\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "E:\workspace\python\untitled\venv\lib\site-packages\frida\core.py", line 58, in get_device_matching
    return Device(self._impl.get_device_matching(lambda d: predicate(Device(d)), raw_timeout))
frida.InvalidArgumentError: device not found

手机已开启USB调试

**Comment by holymonk** [comment]
这是文件编码的问题。我是在macos下编辑的，默认编码是utf8，你的环境应该是windows吧，把文件用gbk转存下就行了。
